lista = [8,2,8, 'Ana are mere', 4.2, True]
print(lista[6:7])
print(len(lista))
print(lista[2:8])
print(lista[-1])
print(lista[-6])
print(lista[-6:])
print(lista[-6:-3])
print(lista[2:8])
print(lista[2:8:2])
lista.append(5.6)
print(lista)
print(lista)
lista.reverse()
print(lista)